require("lucas.plugins-setup")
require("lucas.core.options")
require("lucas.core.keymaps")
require("lucas.core.colorscheme")
require("lucas.plugins.nvim-tree")
require("lucas.plugins.nightfox")
-- require("lucas.plugins.dracula")
-- require("lucas.plugins.onedark")
require("lucas.plugins.lualine")
require("lucas.plugins.telescope")
require("lucas.plugins.autopairs")
require("lucas.plugins.treesitter")
require("lucas.plugins.lsp")
