#!/usr/bin/env bash

languages=$(echo "golang solidity nodejs javascript tmux typescript zsh cpp c lua rust python bash php haskell css html gdb" | tr " " "\n")

core_utils=$(echo "find man tldr sed awk tr cp ls grep xargs rg ps mv kill lsof less head tail tar cp rm rename jq cat ssh cargo git git-worktree git-status git-commit git-rebase docker docker-compose stow chmod chown make" | tr " " "\n")

selected=$(echo -e "$languages\n$core_utils" | fzf)

if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter query: " query

if echo "$languages" | grep -qs $selected; then 
    query=`echo $query | tr ' ' '+'`
    tmux split-window -h bash -c "curl cht.sh/$selected/$query | less -f -r"
else 
    tmux neww bash -c "curl -s cht.sh/$selected~$query | less -f -r" 
fi
