#!/bin/sh
while read -r file
do
        case "$1" in
        "w") feh --bg-scale "$file" & ;;
        "d")
		    prompt "Really delete $file?" "rm $file && notify-send $file deleted." ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "R")
		    convert -rotate -90 "$file" "$file" ;;
        "y")
		    printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		    notify-send "$file copied to clipboard" & ;;
        "g")	ifinstalled gimp && setsid -f gimp "$file" ;;
	    "i")	notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
        esac
done
